---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
library(tidyverse)
```

```{css}
h2 {
  color: navy;
}

p {
  font-size: 16px;
  line-height: 1.5;
}
```


## Studying Questionnaire

```{r}
url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vS5f6plFDiTzY8lfDc88EGc7qPRFbjhQD-l0425xUna4k59-0F0MbIbxB4LLvS_dlIOzgZg3JskUdeH/pub?gid=1974443098&single=true&output=csv"
logged_data <- read_csv(url)

latest_data <- rename(logged_data, 
  study_session_rating = `How effective was your study session?`,
  prefer_morning_study = `Do you prefer to study in the morning?`,
  enjoy_studying = `Does studying make you feel better?`
)

study_session_rate <- latest_data$study_session_rating
average_study_rating <- mean(study_session_rate)
minimum_study_rating <- min(study_session_rate)

latest_data %>%
  ggplot() +
  geom_bar(aes(x = prefer_morning_study))

latest_data %>%
  ggplot() +
  geom_bar(aes(x = enjoy_studying))


```

The average rating for study session effectiveness is **`r round(average_study_rating, 2)`**.  
The lowest rating given was **`r minimum_study_rating`**.

---


